name: Update bookshelf

on:
  push:
    branches: main
    paths: isbns.json

jobs:
  gen_books:
    name: Generate books.json
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - working-directory: scripts
        run: |
          pip install -r requirements.txt
          python gen_books.py

      - uses: actions/upload-artifact@v4
        with:
          name: books.json
          path: books.json

  gen_readme:
    needs: gen_books
    name: Generate README.md
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: books.json

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - working-directory: scripts
        run: |
          pip install -r requirements.txt
          python gen_readme.py

      - uses: actions/upload-artifact@v4
        with:
          name: README.md
          path: README.md

  push_artifacts:
    needs: gen_readme
    name: Push artifacts
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: books.json

      - uses: actions/download-artifact@v4
        with:
          name: README.md

      - id: has_no_changes
        run: |
          git add --intent-to-add .
          git diff --exit-code
        continue-on-error: true

      - if: steps.has_no_changes.outcome == 'failure'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m '🤖 update bookshelf'
          git push
