name: Reply

on:
  issues:
    types: [opened, labeled]

jobs:
  comment_issue_title:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const issue = context.payload.issue;
            const labels = issue.labels.map(label => label.name);
            if (labels.includes('purchase request')) {
              const isbn = issue.title;
              const thumbnail = (await fetch(`https://www.googleapis.com/books/v1/volumes?q=isbn:${isbn}`)).json()['items'][0]['volumeInfo']['imageLinks']['thumbnail'];
              await github.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                body: `![](${thumbnail})`,
              });
            }
